version: 2

project_name: ip-detector

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./main.go
    binary: ip-detector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    flags:
      - -trimpath

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - LICENSE
      - README.md

  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - LICENSE
      - README.md

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-arm64"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## IP Detector {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release of IP Detector!

  footer: |
    ## Docker Images
    
    Docker images are available at:
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}`
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest`
    
    ## Installation
    
    ### Download binary
    1. Download the appropriate binary for your platform from the assets below
    2. Make it executable: `chmod +x ip-detector`
    3. Run: `./ip-detector`
    
    ### Docker
    ```bash
    docker run -p 8080:8080 ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}
    ```
    
    ### Go Install
    ```bash
    go install github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}@{{ .Tag }}
    ```

  name_template: "{{.ProjectName}}-v{{.Version}}"

nfpms:
  - id: packages
    package_name: ip-detector
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    maintainer: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    description: |-
      IP Detector - A simple HTTP service to detect client IP addresses
      with support for various proxy headers and detailed IP information.
    license: "AGPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - ca-certificates
    recommends:
      - git
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/ip-detector/copyright
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/ip-detector/README.md
        file_info:
          mode: 0644

brews:
  - name: ip-detector
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    description: "IP Detector - A simple HTTP service to detect client IP addresses"
    license: "AGPL-3.0"
    test: |
      system "#{bin}/ip-detector --version"
    install: |-
      bin.install "ip-detector"

aurs:
  - name: ip-detector-bin
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    description: "IP Detector - A simple HTTP service to detect client IP addresses"
    maintainers:
      - "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    license: "AGPL-3.0"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/ip-detector-bin.git"
    package: |-
      # bin
      install -Dm755 "./ip-detector" "${pkgdir}/usr/bin/ip-detector"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ip-detector/LICENSE"

winget:
  - name: ip-detector
    publisher: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    license: "AGPL-3.0"
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    short_description: "IP Detector - A simple HTTP service to detect client IP addresses"
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
