FROM scratch

COPY ip-detector /ip-detector
COPY LICENSE /LICENSE
COPY README.md /README.md

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD ["/ip-detector", "-health-check"] || exit 1

ENTRYPOINT ["/ip-detector"]
