FROM scratch

COPY myip /myip
COPY LICENSE /LICENSE
COPY README.md /README.md

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD ["/myip", "-health-check"] || exit 1

ENTRYPOINT ["/myip"]
